### ISSUE TITLE
Can't download one mod 

### ISSUE THREAD

**Issue by rocca91** [Sigourn/iheartnewvegas#12]
Having some trouble with the wabbajack install, it can't get Just assorted mods INI.zip I did try downloading from the guide, but it doesn't recognize it. Any ETA when it will be fixed?

**Comment by Sigourn** [comment]
I'll fix it ASAP, thank you for the report!

**Comment by Sigourn** [comment]
It should work as intended now. Please redownload the Wabbajack and confirm.

**Comment by rocca91** [comment]
Yes thanks for that it works now.
