### ISSUE TITLE
.45 ammo recipes are missing

### ISSUE THREAD

**Issue by vgl266** [Sigourn/iheartnewvegas#6]
So the devs decided to tie availability of .45 auto ammo recipes to the Southern Passage map marker's "discovered" status (I know, very nice game design). Guess what the "Less Map Markers" mod did to this particular marker?
The solution is to remove the part touching that marker from the mod. I will inform mod author of this problem myself, you don't need to bother, but for now this should be mentioned in the guide.

**Comment by Sigourn** [comment]
Thanks! I'll see about addressing this.

**Comment by Sigourn** [comment]
There's actually a bigger issue, which is that Miscellaneous Tweaks does the same thing to hide recipes, instead of tying it to a quest as the others do.

I'll address this in Miscellaneous Tweaks altogether.

**Comment by Sigourn** [comment]
Fixed with my updated Miscellaneous Tweaks Collection Tweaked.
